# Generated by Django 5.1.6 on 2025-03-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_number",
                    models.PositiveIntegerField(verbose_name="table number"),
                ),
                ("dishes", models.JSONField(default=[], verbose_name="list of dishes")),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="total price",
                    ),
                ),
                (
                    "status_order",
                    models.CharField(
                        choices=[
                            ("cooking", "Cooking"),
                            ("ready", "Ready"),
                            ("paid", "Paid"),
                        ],
                        default="cooking",
                        max_length=20,
                        verbose_name="order status",
                    ),
                ),
            ],
        ),
    ]
